### PR TITLE
renaming accessType enum to accessManagementType

### PR DESCRIPTION
**Pull request by rebeccabrennan**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/AM-217

### CODE REVIEW

**Comment by geek-soft** [comment]
Why is that rename needed @rebeccabrennan? A `AccessType` name fits the options and `Management` does not add any value IMO, just  making name longer.

**Comment by rebeccabrennan** [comment]
renaming as we now have AccessManagementType which is EXPLICIT or ROLE_BASED and we now have AccessType which is USER or ROLE

**Comment by rebeccabrennan** [comment]
AccessType changed to AccessorType in pull request feat: support for relationship between user and resource in explicit access record #112

**Comment by geek-soft** [comment]
Closing as it is not viable option.

**Pull request closed without merging**
